config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'animals/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "animals#index"
  get 'animals/search'

  resources :animals do
    resources :tweets, only: [:index, :create, :show, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :new]
  end
  
  resources :tweets, only: [:index, :create, :show, :destroy] do
    resources :messages, only: [:new, :create]
  end


  resources :users, only: :index

  
end

app/models/animal.rb
class Animal < ApplicationRecord
  with_options presence: true do
    validates :animal_name
    validates :animal_type_id, numericality: { other_than: 1 }
    validates :animal_pedigree
    validates :birthday
    validates :introduction
    validates :user
    validates :image
  end
  
  belongs_to :user
  has_one_attached :image
  has_many :tweets, dependent: :destroy
  has_many :likes
  has_many :comments, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :animal_type
end

app/models/animal_type.rb
class AnimalType < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '犬'},
    { id: 3, name: '猫'},
    { id: 4, name: '鳥'},
    { id: 5, name: '小動物'},
    { id: 6, name: 'その他'},
  ]
  include ActiveHash::Associations
  has_many :animals
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  with_options presence: true do
    validates :comment_text
    validates :user
    validates :animal
  end

  belongs_to :user
  belongs_to :animal
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :animal

  validates_uniqueness_of :animal_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord

  with_options presence: true do
    validates :message_text
    validates :user
    validates :tweet
  end

  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  with_options presence: true do
    validates :title
    validates :text
    validates :user
    validates :animal
    validates :food_image
  end

  belongs_to :user
  belongs_to :animal
  has_one_attached :food_image
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  with_options presence: true do
    validates :name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, }
    validates :nickname
  end

  VALID_PASSWORD_REGEX = /(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]/
  validates :password, format: { with: VALID_PASSWORD_REGEX }  

  has_many :animals
  has_many :tweets
  has_many :messages
  has_many :likes
  has_many :comments
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :search_animal, only: [:index, :search]

  def index
    @animals = Animal.includes(:user)
    @tweets = Tweet.includes(:user)
    set_animal_column
  end

  def new
    @animal = Animal.new
  end

  def create
    @animal = Animal.new(animal_params)
    if @animal.save
      redirect_to root_path     
    else
      render :new
    end
  end

  def show
    @animal = Animal.find(params[:id])
    @tweet = @animal.tweets.includes(:user)
    @comment = Comment.new
    @comments = @animal.comments.order(created_at: :desc) #コメントを作成順に取ってくる
  end

  def edit
    @animal = Animal.find(params[:id])
  end

  def update
    @animal = Animal.find(params[:id])
    if @animal.update(animal_params)
      redirect_to animal_path
    else
      render :edit
    end
  end

  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    redirect_to root_path
  end

  def search 
    @results = @p.result.includes(:user)
  end

  private
  def animal_params
    params.require(:animal).permit(:animal_name, :animal_type_id, :animal_pedigree, :birthday, :introduction, :image).merge(user_id: current_user.id)
  end

  def search_animal
    @p = Animal.ransack(params[:q])
  end

  def set_animal_column
    @animal_name = Animal.select("animal_name").distinct
    @animal_pedigree = Animal.select("animal_pedigree").distinct
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @animal = Animal.find(params[:animal_id])
    @comment = @animal.comments.new(comment_params)
    if @comment.save
      ActionCable.server.broadcast 'comment_channel', content: @comment
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:comment_text).merge(user_id: current_user.id, animal_id: params[:animal_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like

  def create
    like = current_user.likes.new(animal_id: @animal.id)
    like.save
    likes = Like.where(animal_id: @animal.id)
  end

  def destroy
    like = Like.find_by(animal_id: @animal.id, user_id: current_user.id).destroy
    likes = Like.where(animal_id: @animal.id)
  end

  private

  def set_like
    @animal = Animal.find(params[:animal_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @message = @tweet.messages.new(message_params)
    if @message.save
      ActionCable.server.broadcast 'message_channel', content: @message
    end
  end

  private
  def message_params
    params.require(:message).permit(:message_text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  def index
    @tweet = Tweet.includes(:animal_id)
    @tweets = Tweet.new

  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      render 'index'
    end
  end

  def show
    @animal = Animal.find(params[:id])
    @tweet = Tweet.find(params[:animal_id])
    @message = Message.new
    @messages = @tweet.messages.includes(:user)
  end

  def destroy
    @tweet = Tweet.find(params[:animal_id])
    @tweet.destroy
    redirect_to root_path
  end


  private

  def tweet_params  
    params.require(:tweet).permit(:title, :text, :food_image).merge(user_id: current_user.id, animal_id: params[:animal_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @animals = Animal.where(user_id: current_user.id)
  end

end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/animals/edit.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('image6-2.png' , size: '185x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">ペットの情報を記入してね</h2>
    <%= form_with model: @animal, local: true do |f| %>

    
    <%= render 'shared/error_messages', model: f.object %>
    

    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        ペットの画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
        <div id="image-list"></div>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        ペットの名前
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :animal_name, class:"items-text", id:"item-name", placeholder:"（例）チロル", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          ペットの紹介
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :introduction, class:"items-text", id:"item-info", placeholder:"ペットの紹介（1,000文字まで）（例）我が家の可愛いチロルです！毎日毎日癒されています。遊ぶことが大好きで、仕事から帰ると「遊んでくれ〜！」とやってきます。大変な部分もありますが、とても楽しい毎日です。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="form">
        <div class="weight-bold-text">
          ペットの種類
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:animal_type_id, AnimalType.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          ペットの品種
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :animal_pedigree, class:"items-text", id:"item-sales-status", placeholder:"（例）トイプードルなど" %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <div class="items-detail">
      
      <div class="form">
        <div class="weight-bold-text">
          ペットの誕生日
          <span class="indispensable">必須</span>
        </div>
        <%= raw sprintf(
            f.date_select(
              :birthday,
              class:'select-box',
              id:"item-shipping-fee-status",
              use_month_numbers: true,
              prompt:'--',
              start_year: 1930,
              end_year: (Time.now.year - 5),
              date_separator: '%s'),
              "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
             
      </div>
    </div>
    <%# /配送について %>
     <%= link_to image_tag"image6-2.png", class: "animal-image1"%>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  

  <footer class="items-sell-footer">
    <%= link_to image_tag('image1-2-3.png' , size: '185x50'), "/" %>
    <p class="inc">
      Animal Blog
    </p>
  </footer>
</div>

app/views/animals/index.html.erb
<div class='main'>

  <div class='title-contents'>
  

  <div class="search-title-content">
  
      <div class='navs'>
        <ul class='lists-lefts'>
          <% if signed_in? %>
          <li><%= link_to '登録したペット一覧', users_path, class: "brand-lists" %></li>
          <li><%= link_to current_user.nickname, "#", class: "user-nicknames" %></li> 
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logouts" %></li> 
          <% else %>
          <li><%= link_to 'ログイン', new_user_session_path, class: "logins" %></li>
          <li><%= link_to '新規登録', new_user_registration_path, class: "sign-ups" %></li>
          <% end %>
        </ul>
      </div>


       <div class="search-contents">
        <%= search_form_for @p, url: animals_search_path, class: 'search-forms' do |f| %>
          <%= f.label :animal_eq, '[ペットの名前で検索]', class: 'input-boxs'%> 
          <%= f.collection_select :animal_name_eq, @animal_name, :animal_name, :animal_name, include_blank: '指定なし' %>
          <button class="search-buttons">
            <%= image_tag "search.png", class:"search-icons" %>
          </button>
        </form>
        <% end %>
  


        <%= search_form_for @p, url: animals_search_path, class: 'search-forms' do |f| %>
          <%= f.label :animal_pedigree_eq, '[ペットの品種で検索]', class: 'input-boxs'%> 
          <%= f.collection_select :animal_pedigree_eq, @animal_pedigree, :animal_pedigree, :animal_pedigree, include_blank: '指定なし' %>
          <button class="search-buttons">
            <%= image_tag "search.png", class:"search-icons" %>
          </button>
        </form>
        <% end %>
      </div>

   </div>

    <h2 class='service-title'>
      Animal Blog へようこそ！！！！
    </h2>
    <p class='service-explain'>
      誰でも可愛いペットを紹介できる
    </p>
    <p class='service-explain'>
      ペットの繋がりを大切に
    </p>

  </div>
  
  <div class='select-reason-contents'>
    <h2 class='title'>
      アニマルブログで使用できるサービスについて
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "image1-1-1.png", class:"list-animal" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>ペット</span>
          の登録
        </h3>
        <p class='reason-list-description'>
          ペットの自慢をしよう！まずは、右下のアイコンから、ペットを登録してね
        </p>
      </li>
      <li class='list'>
        <%= image_tag "image4-1.png", class:"list-animal" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>ペット</span>
          のツイート
        </h3>
        <p class='reason-list-description'>
          みんなでペットについて語り合う！登録した子の詳細ページからツイート投稿できるよ
        </p>
      </li>
      <li class='list'>
        <%= image_tag "image6-1.png", class:"list-animal" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>ペット</span>
          の繋がり
        </h3>
        <p class='reason-list-description'>
          なんでも繋がりは大事！ペットの良いお友達が見つかるかも！
        </p>
      </li>
    </ul>
  </div>
  
  <div class='ad-contents'>
     <%= link_to image_tag("image6-2.png", class:"animal-image"), "#" %>
    <h2 class='ad-title'>
      ペットのツイート一覧
    </h2>
  </div>
  
  <div class='feature-contents'>
   
    <h2 class='title'>
      みんな可愛いね
    </h2>
    <div class='feature-title'>
    <% @tweets.last(7).each do |tweet| %>
    <%= link_to animal_tweet_path(tweet.id, tweet.animal_id) do %>
    <ul class='feature-lists'>
      <li class='list'>
        <% if tweet.food_image.content_type.include?('image/') %>
          <%= image_tag tweet.food_image, class:"list-pict" %>
        <% elsif tweet.food_image.content_type.include?('video/') %>
          <%= video_tag url_for(tweet.food_image), controls: true, class:"list-pict" %>
        <% end %>
          
        <h3 class='feature-list-text'>
          <%= tweet.title %>
        </h3>
    </ul>
    <% end %>
    <% end %>
    </div>
  </div>

  <div class='animal-contents'>
    <%= link_to image_tag "image0-4.png", class:"animal-image"%>
    <h1 class="ad-title">人気のペット一覧</h1>
  </div>

  <div class='feature-contents'>
    <div class='feature-title'>
    <% @animals.last(7).each do |animal| %>
    <%= link_to animal_path(animal.id) do %>
    <ul class='feature-lists'>
      <li class='list'>
        <% if animal.image.content_type.include?('image/')%>
          <%= image_tag animal.image, class:"list-pict" %>
        <% elsif animal.image.content_type.include?('video/') %>
          <%= video_tag rails_blob_path(animal.image), controls: true, class:"list-pict" %>
        <% end %>
        <h3 class='feature-list-text'>
          <%= animal.animal_name %>
        </h3>
        <p class='feature-list-description'>
          <%= animal.animal_type.name %>
        </p>
        <p class='feature-list-description'>
          <%= animal.animal_pedigree %>
        </p>      
    </ul>
    <% end %>
    <% end %>
    </div>
  </div> 
    
</div>
 
<% if user_signed_in? %>
  <%= link_to new_animal_path, class: 'purchase-btn' do %>
    <span class='purchase-btn-text'>登録する</span>
  <% end %>
<% end %>


<%= render "shared/second-footer" %>
<% breadcrumb :root %>

app/views/animals/search.html.erb
<%= render "shared/second-header"%>

<div class='search-animal-content'%>
  <div class='feature-contents'> 
    <h2 class='title'>
      検索結果
    </h2>
    <div class='feature-title'>
    <% if @results.length !=0 %>
    <% @results.each do |result| %>
    <%= link_to animal_path(result.id) do %>
    <ul class='feature-lists'>
      <li class='list'>
        <% if result.image.content_type.include?("image/") %>
        <%= image_tag result.image, class:"list-pict" %>
        <% elsif result.image.content_type.include?("video/") %>
        <%= video_tag url_for(result.image), controls: true, class:"list-pict" %>
        <% end %>
        <h3 class='feature-list-text'>
          <%= result.animal_name %>
        </h3>
        <p class='feature-list-description'>
          <%= result.animal_type.name %>
        </p>
        <p class='feature-list-description'>
          <%= result.animal_pedigree %>
        </p>
    </ul>
    <% end %>
    <% end %>
    <% end %>
    </div>
  </div>
</div>

  <%= render "shared/second-footer"%>
  <%= link_to 'トップページへ戻る', root_path %>

  <% breadcrumb :animal_search %>

app/views/animals/show.html.erb
<%= render "shared/second-header" %>

<div class= animals>
  <div class="item-show">
    <div class="item-box">
      <h2 class="name">
        <%= @animal.animal_name %>
      </h2>
      <div class="item-img-content">
        <% if @animal.image.content_type.include?('image/') %>
          <%= image_tag @animal.image,class:"item-box-img" %> 
        <% elsif @animal.image.content_type.include?('video/') %>
          <%= video_tag url_for(@animal.image), controls: true %>
        <% end %>
      </div>


      <div class="detail-tables">          
         <div class="detail-items">飼い主さん<p><%= @animal.user.nickname %></p></div>            
         <div class="detail-items-1">ペットの名前<p><%= @animal.animal_name %></p></div>                  
         <div class="detail-items-2">ペットの種類<p><%= @animal.animal_type.name %></p></div>
         <div class="detail-items-3">ペットの品種<p><%= @animal.animal_pedigree %></p></div>           
         <div class="detail-items-4">ペットの年齢<p><%= @animal.birthday %></p></div>                
      </div>

      <div class="detail-items-5">ペットの紹介</div>
         <div class="detail-items-5-1">
           <%= @animal.introduction %>
         </div>

         <div id="like-<%= @animal.id %>">   
           <%= render 'likes/like', { animal: @animal} %>
         </div>
      </div> 


    

    <div class="comment-box">
    
      <%= image_tag "image100.png", class:"comment-image"%>
      
      <%= form_with model: @comment, url: animal_comments_path(@animal.id), local: true do |f| %>
        <%= f.text_field :comment_text, class: "comment-text" %> 
        <div class="message-text"id='comments'>
          <% @comments.reverse_each do |comment| %>
          <% if comment.user_id == current_user.id %>
            <div class="current-user-message">
            <p><%= image_tag comment.animal.image, size: '40x40' %><%= comment.comment_text %>(<%= comment.user.nickname %>)</p>
            </div>
            <% else %>
            <div class="current-user-messages">
            <p><%= comment.comment_text %>(<%= comment.user.nickname %>)<%= image_tag comment.animal.image, size: '40x40' %></p>
            </div>
          <% end %>
          <% end %>
            <button>投稿</button>
            <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
            <span>コメントする<span>
          <% end %>
          </div>     
              
        <%= image_tag "image0-2-1.jpeg", class:"comment-image"%>
    </div>

  <div class='animal-red-btn'>
    <% if user_signed_in? && current_user.id == @animal.user_id %>
      <%= link_to "ペット情報の編集", edit_animal_path(@animal.id), method: :get, class: "item-red-btn" %>
      <p class="or-text">or</p>
      <%= link_to "削除", animal_path(@animal.id), method: :delete, class:"item-destroy" %>
    <% end %>
  </div>
      <%= link_to "ツイート一覧画面に進む", "#" ,class:"item-red-btn-1"%>     
</div>  

      

      <% unless @tweet.blank? %>
      <p class="animal-tweet-name">
      <% @tweet.last(1).each do |tweet| %>
            <%= tweet.animal.animal_name %><p>のツイート一覧</p>
            </p>
            <% end %>
          <div class='feature-contents'>
            <div class='feature-title'>
            <% @tweet.each do |tweet| %>
            <%= link_to animal_tweet_path(tweet.id) do %>
            <ul class='feature-lists'>
              <li class='list'>
              <% if tweet.food_image.content_type.include?('image/') %>
                <%= image_tag tweet.food_image, class:"list-pict" %>
              <% elsif tweet.food_image.content_type.include?('video/') %>
                <%= video_tag url_for(tweet.food_image), controls: true, class: 'list-pict' %>
              <% end %>
                <h3 class='feature-list-text'>
                  <%= tweet.animal.animal_name %>
                </h3>
                <p class='feature-list-description'>
                  <%= tweet.title %>
                </p>
            </ul>
            <% end %>
            <% end %>    
            </div>
          </div> 
      <% end %>
        
        <% if user_signed_in? && current_user.id == @animal.user_id %>
          <%= link_to animal_tweets_path(@animal.id), class: 'purchase-btn' do %>
            <span class='purchase-btn-text'>投稿する</span>
          <% end %>
        <% end %>

 

  

<%= render "shared/second-footer" %>

<% breadcrumb :animals %>

app/views/likes/_like.html.erb
<%if user_signed_in? %>
  <% if Like.find_by(user_id: current_user.id, animal_id: animal.id) %>
    <%=link_to animal_like_path(animal, animal.likes), {method: "delete", remote: true, class: "likes-count"} do %>
   <div class = "iine_button">❤️<%= animal.likes.count %></div>
    
  <% end %>
  <% else %>
   <%=link_to animal_likes_path(animal), {method: "post", remote: true, class: "likes-count"} do %>
  <div class = "iine_button">♡️<%= animal.likes.count %>
     <% end %>
  <% end %>
  <% else %>
    <%= animal.likes.count %>
<% end %>

app/views/likes/create.js.erb
$("#like-<%= @animal.id %>").html("<%= j(render partial: 'like', locals: { animal: @animal }) %>");

app/views/likes/destroy.js.erb
$("#like-<%= @animal.id %>").html("<%= j(render partial: 'like', locals: { animal: @animal }) %>");

app/views/tweets/index.html.erb
<%= render 'shared/second-header'%>

<div class="items-sell-contents">
  <header class="items-sell-header">

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">ペットのツイート</h2>
    <%= form_with model: @tweets, url: animal_tweets_path, local: true do |f| %>

    
    <%= render 'shared/error_messages', model: f.object %>
   

    
    <div class="img-upload">
      <div class="weight-bold-text">
        ペットの画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :food_image, id:"item-image" %>
        <div id="image-list"></div>
      </div>
    </div>
    
    <div class="new-items">
      <div class="weight-bold-text">
        ツイートのタイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"（例）チロル", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          ツイートの内容
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"items-text", id:"item-info", placeholder:"ペットの紹介（1,000文字まで）（例）我が家の可愛いチロルです！毎日毎日癒されています。遊ぶことが大好きで、仕事から帰ると「遊んでくれ〜！」とやってきます。大変な部分もありますが、とても楽しい毎日です。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    
     <%= link_to image_tag"image6-2.png", class: "animal-image1"%>

    
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
   
  </div>
  <% end %>
</div>

<%= render 'shared/second-footer'%>

<% breadcrumb :animal_tweet %>

app/views/tweets/show.html.erb
<%= render "shared/second-header" %>


<div class= animals>
  <div class="item-show">
    <div class="item-box">
    
      <h2 class="name">
        <%= @tweet.animal.animal_name %>
      </h2>

      <div class="item-img-content">
        <% if @tweet.food_image.content_type.include?('image/') %>
          <%= image_tag @tweet.food_image, class:"item-box-img" %>
        <% elsif @tweet.food_image.content_type.include?('video/') %>
          <%= video_tag url_for(@tweet.food_image),controls: true %> 
        <% end %>
      </div>

      <div class="detail-tables">
      
          
            <div class="detail-items">飼い主さん<p><%= @tweet.user.nickname %></p></div>
            
            <div class="detail-items-1">ペットの名前<p><%= @tweet.animal.animal_name %></p></div>
                   
            <div class="detail-items-2">ペットの種類<p><%= @tweet.animal.animal_type.name %></p></div>

            <div class="detail-items-3">ペットの品種<p><%= @tweet.animal.animal_pedigree %></p></div>
             
            <div class="detail-items-4">ペットの年齢<p><%= @tweet.animal.birthday %></p></div>
                 
      </div>


      <h1>タイトル</h1>
          <div class="detail-items-6"><%= @tweet.title %></div>
          <h1>ツイートの内容<h1>
         <div class="detail-items-6-1"><%= @tweet.text %></div>
                      
    </div>


    <div class="comment-box">
    
      <%= image_tag "image100.png", class:"comment-image"%>
      
      <%= form_with model: @message, url: tweet_messages_path(@tweet.id), local: true do |f| %>
        <%= f.text_field :message_text, class: "comment-text" %> 
        <div class="message-text"id='messages'>
          <% @messages.reverse_each do |message| %>
          <% if message.user_id == current_user.id %>
            <div class="current-user-message">
            <p><%= message.message_text %>(<%= message.user.nickname %>)</p>
            </div>
            <% else %>
            <div class="current-user-messages">
            <p><%= message.message_text %>(<%= message.user.nickname %>)</p>
            </div>
          <% end %>
          <% end %>
            <button>投稿</button>
            <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
            <span>コメントする<span>
          <% end %>
          </div>     
              
        <%= image_tag "image0-2-1.jpeg", class:"comment-image"%>
    </div>
  

 <%= link_to "この子の紹介ページへ", animal_path(@animal.id) ,class:"item-red-btn"%>
    <% if user_signed_in? && current_user.id == @tweet.user_id %>
      <%= link_to "削除", animal_tweet_path(@tweet.id), method: :delete, class:"item-destroy" %>
    <% end %>

      
      <%= link_to "ツイート一覧画面に進む", "#" ,class:"item-red-btn"%>
     
</div>
     

<%= render "shared/second-footer"%>

<% breadcrumb :tweets %>